# Generated by Django 4.2 on 2025-06-19 18:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
